#!/bin/bash

## Get data
STATUS="$(mpc status)"
COVER="$HOME/Music/library/default.jpg"
MUSIC_DIR="$HOME/Music"

## Get status
get_status() {
	if [[ $STATUS == *"[playing]"* ]]; then
		echo " "
	else
		echo " "
	fi
}

## Get song
get_song() {
	song=`mpc -f %title% current`
	if [[ -z "$song" ]]; then
		echo "Offline"
	else
		echo "$song"
	fi	
}

## Get artist
get_artist() {
	artist=`mpc -f %artist% current`
	if [[ -z "$artist" ]]; then
		echo "Offline"
	else
		echo "$artist"
	fi	
}

## Get time
get_time() {
    percent=$(mpc status | grep -oP '\(\K[0-9]+(?=%\))')

    # If empty, return 0
    if [[ -z "$percent" ]]; then
        echo "0"
    else
        echo "$percent"
    fi
}

get_ctime() {
	ctime=`mpc status | grep "#" | awk '{print $3}' | sed 's|/.*||g'`
	if [[ -z "$ctime" ]]; then
		echo "0:00"
	else
		echo "$ctime"
	fi	
}
get_ttime() {
    time=$(mpc status | grep -oP '\(\K[0-9]+(?=%\))')
    echo "${time:-0}"
}

## Get cover
get_cover() {
    FILE="$MUSIC_DIR/$(mpc current -f %file%)"

    # Extract the attached image (stream 0:1)
    if ffmpeg -loglevel error -i "$FILE" -map 0:1 -c copy "$COVER" -y 2>/dev/null; then
        echo "$COVER"
    else
        echo "$HOME/Music/library/default.jpg"
    fi
}


## Execute accordingly
if [[ "$1" == "--song" ]]; then
	get_song
elif [[ "$1" == "--artist" ]]; then
	get_artist
elif [[ "$1" == "--status" ]]; then
	get_status
elif [[ "$1" == "--time" ]]; then
	get_time
elif [[ "$1" == "--ctime" ]]; then
	get_ctime
elif [[ "$1" == "--ttime" ]]; then
	get_ttime
elif [[ "$1" == "--cover" ]]; then
	get_cover
elif [[ "$1" == "--toggle" ]]; then
	mpc -q toggle
elif [[ "$1" == "--next" ]]; then
	{ mpc -q next; get_cover; }
elif [[ "$1" == "--prev" ]]; then
	{ mpc -q prev; get_cover; }
fi
